travis:
  secure:
    BINSTAR_TOKEN: EswiPoqTrk4/jYPB6GhA25lCAbujNUZYg5OZyVyTCXtbm1u06YkEaT1u73VMkzPDMO1Ic2HGNPtf0DW0e7RNSCV/wlVLGmuYOa2s+xFvMmpVECihupTBGhmUjoR4yM1p8iVZs7KzH+NOT0iq2rUT/wFJLQFDECx8vjgoz/NbdTutebZdgQVcCp7uyF/LW7bbABHakgR0K+j4v7C6cmna/x0BVuNLvcVc/SizwQDTILbDFKzMvjCONUhgku0BKXDGq5JZV71W+j2k6I+XqmQfoLreguOEGyG5Si8YZW85k4BufyCpVq5rmkGFroDLnMlLD6HZCJReIjIV7Eib3zLLbcBDeL4d9GAaOfCaNZFgtzS0VqjzBFwgG+nPOz+jTqb9uKWp/zy5nv2aYj5rEDpsTvDBHWKliuGo+zFDwk3VsmZYGlzokz15fYLfeahxfmqJo5S6E/6dbO1SQOh3l5W0+bezRLnAShqKM2TRLVc8BwRB8uCwUkamUbgnipoX7B2dwKYiid/S7hwDX8W9+ZQxik8E5OlkHpfBWrPOnK9NU7C8wvq1Q1/KSQroDk4Jnwp6/YdoeyTrzGuC5ggwrfqC352MZVii/LwyRyzqxizwPZJAcF8selF3pWSjYqvE+DxCH+SYqzMW2iqZrvaIRqeHexcxbvBJAsSeh/UKADHi6p0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
